version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mrd_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mrd_db
      POSTGRES_USER: caiofugii
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
